import { Schema, Table, Column } from "./types";

function buildConstraints(col: Column): string {
  const parts: string[] = [];
  if (col.primaryKey) parts.push("primary key");
  if (col.unique) parts.push("unique");
  if (col.references) parts.push(`fk → ${col.references.table}.${col.references.column}`);
  if (col.defaultValue) parts.push(`default: ${col.defaultValue}`);
  if (col.nullable) parts.push("nullable");
  return parts.join(", ");
}

function buildTableSection(table: Table): string {
  const header = `### ${table.name}\n${table.description}\n`;
  const colHeader = "| Column | Type | Constraints |\n|--------|------|-------------|\n";
  const colRows = table.columns
    .map((col) => `| ${col.name} | ${col.type} | ${buildConstraints(col)} |`)
    .join("\n");
  return `${header}\n${colHeader}${colRows}`;
}

function buildExampleQueries(table: Table): string {
  const nonPkCols = table.columns.filter((c) => !c.primaryKey);
  const colNames = nonPkCols.map((c) => c.name).join(", ");
  const placeholders = nonPkCols.map(() => "?").join(", ");

  let sql = `**${table.name}**\n\n`;
  sql += "```sql\n";
  sql += `-- Get all ${table.name}\nSELECT * FROM ${table.name};\n\n`;
  sql += `-- Get ${table.name} by ID\nSELECT * FROM ${table.name} WHERE id = ?;\n\n`;
  sql += `-- Create a new record\nINSERT INTO ${table.name} (${colNames}) VALUES (${placeholders});\n`;

  // Add JOIN query for tables with foreign keys
  const fkCols = table.columns.filter((c) => c.references);
  for (const fk of fkCols) {
    const ref = fk.references!;
    sql += `\n-- Get ${table.name} with ${ref.table} info\n`;
    sql += `SELECT t.*, r.*\nFROM ${table.name} t\nJOIN ${ref.table} r ON t.${fk.name} = r.${ref.column}\nWHERE t.id = ?;\n`;
  }

  sql += "```";
  return sql;
}

function buildRelationshipsMap(schema: Schema): string {
  if (schema.relationships.length === 0) return "";
  const typeSymbol: Record<string, string> = {
    "one-to-many": "1──*",
    "many-to-many": "*──*",
    "one-to-one": "1──1",
  };
  const lines = schema.relationships.map((r) => {
    const sym = typeSymbol[r.type] || "──";
    return `  ${r.from} ${sym} ${r.to} (${r.foreignKey})`;
  });
  return `## Relationships Map

\`\`\`
${lines.join("\n")}
\`\`\``;
}

function buildCommonMistakes(schema: Schema): string {
  const mistakes: string[] = [];

  for (const table of schema.tables) {
    const fkCols = table.columns.filter((c) => c.references);
    for (const fk of fkCols) {
      const ref = fk.references!;
      mistakes.push(
        `- When querying \`${table.name}\` with \`${fk.name}\`, always JOIN on \`${ref.table}.${ref.column}\` — do not select \`${fk.name}\` as a raw integer`
      );
    }

    const nullableCols = table.columns.filter((c) => c.nullable && !c.primaryKey);
    for (const col of nullableCols) {
      mistakes.push(
        `- \`${table.name}.${col.name}\` is nullable — use COALESCE or handle NULL when displaying`
      );
    }
  }

  // Warn about common naming confusion
  const tableNames = schema.tables.map((t) => t.name);
  for (const table of schema.tables) {
    const fkCols = table.columns.filter((c) => c.references);
    for (const fk of fkCols) {
      const singularRef = fk.references!.table.replace(/s$/, "");
      if (!table.columns.some((c) => c.name === singularRef)) {
        mistakes.push(
          `- The column is \`${table.name}.${fk.name}\`, not \`${table.name}.${singularRef}\` — always use the exact column name`
        );
      }
    }
  }

  if (mistakes.length === 0) return "";
  return `## Common Mistakes

${mistakes.join("\n")}`;
}

export function generateContext(schema: Schema): string {
  const tableSections = schema.tables.map((t) => buildTableSection(t)).join("\n\n");

  const relationships = schema.relationships
    .map((r) => `- **${r.from} → ${r.to}**: ${r.type} via \`${r.from}.${r.foreignKey}\` — ${r.description}`)
    .join("\n");

  const relationshipsMap = buildRelationshipsMap(schema);
  const commonMistakes = buildCommonMistakes(schema);
  const exampleQueries = schema.tables.map((t) => buildExampleQueries(t)).join("\n\n");

  const tableCount = schema.tables.length;
  const colCount = schema.tables.reduce((sum, t) => sum + t.columns.length, 0);
  const relCount = schema.relationships.length;

  return `# GROUNDWORK.md
# Generated by Groundwork

## Schema: ${schema.name}
${schema.description}

> ${tableCount} tables · ${colCount} columns · ${relCount} relationships

---

## Tables

${tableSections}

---

## Relationships
${relationships}

${relationshipsMap}

---

## AI Instructions

When working with this database schema, follow these rules:

1. Always use the exact table and column names defined above
2. Always include proper foreign key references in queries
3. Use the relationships defined above — do not infer new ones
4. When creating new queries, follow these patterns:

### Example Queries

${exampleQueries}

---

${commonMistakes}

---

## Common Patterns

- **Fetching with relations**: Always JOIN using the foreign keys defined in Relationships
- **Inserting records**: Include all non-nullable columns; let defaults handle timestamps
- **Filtering**: Use indexed columns (primary keys, foreign keys) for WHERE clauses

---

## Rules
- This file is the source of truth for database structure
- Do not modify table names, column names, or types without updating this file
- All queries should be consistent with the schema defined here
- When in doubt, reference this file before writing any database code
`;
}
