import { Schema, Table, Column } from "./types";

function buildConstraints(col: Column): string {
  const parts: string[] = [];
  if (col.primaryKey) parts.push("primary key");
  if (col.unique) parts.push("unique");
  if (col.references) parts.push(`fk → ${col.references.table}.${col.references.column}`);
  if (col.defaultValue) parts.push(`default: ${col.defaultValue}`);
  if (col.nullable) parts.push("nullable");
  return parts.join(", ");
}

function buildTableSection(table: Table): string {
  const header = `### ${table.name}\n${table.description}\n`;
  const colHeader = "| Column | Type | Constraints |\n|--------|------|-------------|\n";
  const colRows = table.columns
    .map((col) => `| ${col.name} | ${col.type} | ${buildConstraints(col)} |`)
    .join("\n");
  return `${header}\n${colHeader}${colRows}`;
}

function buildExampleQueries(table: Table): string {
  const nonPkCols = table.columns.filter((c) => !c.primaryKey);
  const colNames = nonPkCols.map((c) => c.name).join(", ");
  const placeholders = nonPkCols.map(() => "?").join(", ");

  let sql = `**${table.name}**\n\n`;
  sql += "```sql\n";
  sql += `-- Get all ${table.name}\nSELECT * FROM ${table.name};\n\n`;
  sql += `-- Get ${table.name} by ID\nSELECT * FROM ${table.name} WHERE id = ?;\n\n`;
  sql += `-- Create a new record\nINSERT INTO ${table.name} (${colNames}) VALUES (${placeholders});\n`;

  const fkCols = table.columns.filter((c) => c.references);
  for (const fk of fkCols) {
    const ref = fk.references!;
    sql += `\n-- Get ${table.name} with ${ref.table} info\n`;
    sql += `SELECT t.*, r.*\nFROM ${table.name} t\nJOIN ${ref.table} r ON t.${fk.name} = r.${ref.column}\nWHERE t.id = ?;\n`;
  }

  sql += "```";
  return sql;
}

function buildRelationshipsMap(schema: Schema): string {
  if (schema.relationships.length === 0) return "";
  const typeSymbol: Record<string, string> = {
    "one-to-many": "1──*",
    "many-to-many": "*──*",
    "one-to-one": "1──1",
  };
  const lines = schema.relationships.map((r) => {
    const sym = typeSymbol[r.type] || "──";
    // For one-to-many, swap from/to so "one" side comes first (from = FK holder = many side)
    if (r.type === "one-to-many") {
      return `  ${r.to} ${sym} ${r.from} (${r.foreignKey})`;
    }
    return `  ${r.from} ${sym} ${r.to} (${r.foreignKey})`;
  });
  return `## Relationships Map\n\n\`\`\`\n${lines.join("\n")}\n\`\`\``;
}

function buildCommonMistakes(schema: Schema): string {
  const mistakes: string[] = [];

  for (const table of schema.tables) {
    const fkCols = table.columns.filter((c) => c.references);
    for (const fk of fkCols) {
      const ref = fk.references!;
      mistakes.push(
        `- When querying \`${table.name}\` with \`${fk.name}\`, always JOIN on \`${ref.table}.${ref.column}\` — do not select \`${fk.name}\` as a raw integer`
      );
    }

    const nullableCols = table.columns.filter((c) => c.nullable && !c.primaryKey);
    for (const col of nullableCols) {
      mistakes.push(
        `- \`${table.name}.${col.name}\` is nullable — use COALESCE or handle NULL when displaying`
      );
    }
  }

  for (const table of schema.tables) {
    const fkCols = table.columns.filter((c) => c.references);
    for (const fk of fkCols) {
      const singularRef = fk.references!.table.replace(/s$/, "");
      if (!table.columns.some((c) => c.name === singularRef)) {
        mistakes.push(
          `- The column is \`${table.name}.${fk.name}\`, not \`${table.name}.${singularRef}\` — always use the exact column name`
        );
      }
    }
  }

  if (mistakes.length === 0) return "";
  return `## Common Mistakes\n\n${mistakes.join("\n")}`;
}

export function generateContext(schema: Schema): string {
  const tableSections = schema.tables.map((t) => buildTableSection(t)).join("\n\n");

  const relationships = schema.relationships
    .map((r) => {
      // For one-to-many, display as "to → from" (one side → many side), but via still references FK holder
      if (r.type === "one-to-many") {
        return `- **${r.to} → ${r.from}**: ${r.type} via \`${r.from}.${r.foreignKey}\` — ${r.description}`;
      }
      return `- **${r.from} → ${r.to}**: ${r.type} via \`${r.from}.${r.foreignKey}\` — ${r.description}`;
    })
    .join("\n");

  const relationshipsMap = buildRelationshipsMap(schema);
  const commonMistakes = buildCommonMistakes(schema);
  const exampleQueries = schema.tables.map((t) => buildExampleQueries(t)).join("\n\n");

  const tableCount = schema.tables.length;
  const colCount = schema.tables.reduce((sum, t) => sum + t.columns.length, 0);
  const relCount = schema.relationships.length;

  return `# GROUNDWORK.md
# Generated by Groundwork

## Schema: ${schema.name}
${schema.description}

> ${tableCount} tables · ${colCount} columns · ${relCount} relationships

---

## Tables

${tableSections}

---

## Relationships
${relationships}

${relationshipsMap}

---

## Example Queries

${exampleQueries}

---

${commonMistakes}

---

## Instructions

This file is the source of truth for the database schema. You MUST follow these rules:

1. Use the exact table and column names defined in this file — do not guess or infer names
2. Use the relationships defined above — do not invent new foreign keys or associations
3. When JOINing tables, use the foreign keys listed in the Relationships section
4. Include all non-nullable columns when inserting records; let defaults handle timestamps
5. Use indexed columns (primary keys, foreign keys) in WHERE clauses for performance
6. Check the Common Mistakes section before writing any query involving these tables
7. If a column is marked nullable, handle NULL values explicitly (COALESCE, IS NULL checks, or conditional logic)
`;
}
